### ISSUE TITLE
Publish NuGet Package failing on Azure DevOps

### ISSUE THREAD

**Issue by ckenny** [MicrosoftDocs/mslearn-tailspin-spacegame-web-models#7]
Hi,

I am on a learning path and while performing an exercise as on the below given section, I am getting error on Azure DevOps at the time of running pipeline.

https://docs.microsoft.com/en-us/learn/modules/manage-build-dependencies/5-create-package-pipeline

Is there any change in the steps or I need to take care or something?

Attached the log over here...

[log_9_40.zip](https://github.com/MicrosoftDocs/mslearn-tailspin-spacegame-web-models/files/3994823/log_9_40.zip)

**Comment by ckenny** [comment]
> 
> 
> Hi,
> 
> I am on a learning path and while performing an exercise as on the below given section, I am getting error on Azure DevOps at the time of running pipeline.
> 
> https://docs.microsoft.com/en-us/learn/modules/manage-build-dependencies/5-create-package-pipeline
> 
> Is there any change in the steps or I need to take care or something?
> 
> Attached the log over here...
> 
> [log_9_40.zip](https://github.com/MicrosoftDocs/mslearn-tailspin-spacegame-web-models/files/3994823/log_9_40.zip)

I got a solution from this one,

[https://stackoverflow.com/questions/58856604/azure-devops-publish-nuget-to-hosted-feed](https://stackoverflow.com/questions/58856604/azure-devops-publish-nuget-to-hosted-feed)

I have done two changes like below,

1. In the FeedSetting Permissions, selected "Allow project-scoped builds"

2. The YML file updated for NuGetCommand like below,

```
- task: NuGetCommand@2
  displayName: 'Publish NuGet package'
  inputs:
    command: push
    feedsToUse: 'select'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'Space Game - web - Dependencies/Tailspin.SpaceGame.Web.Models'
    allowPackageConflicts: true
```

Cheers,
KC
